### PR TITLE
Fix the search feature, bump dependencies, add dark mode, and more!

### PR DESCRIPTION
**Pull request by Sidd-underscore**
This PR fixes the website, bumps deps, upgrades the code and organizes the files better.

### CODE REVIEW

**Comment by Sidd-underscore** [comment]
Ah, the dependencies are angry. Fixing soon.

**Comment by Sidd-underscore** [comment]
`@hackclub/meta` doesn't support react^18.2.0 (smh), so I'll use [Nextjs's built-in metadata](https://nextjs.org/docs/app/building-your-application/optimizing/metadata) feature

**Comment by Sidd-underscore** [comment]
And that's everything done!

**Review by Arpan-206 — APPROVED** [review]

**Comment by Arpan-206** [comment]
tysm @Sidd-underscore!

**Comment by Sidd-underscore** [comment]
No worries!!

**Pull request merged**
